version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:9000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - my-laravel-network
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    #entrypoint: [ "bash", "-c", "chmod 750 -R /var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: vagas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - "psqldata:/var/lib/postgresql/data"
    networks:
      - my-laravel-network

networks:
  my-laravel-network:
    driver: bridge
volumes:
  psqldata: